# -*- coding: utf-8 -*-
"""
Post-processing helper for full recomputation.

It copies selected CSV/PNG outputs from run_full_strict_extension into
recomputed_results/ and creates canonical aliases used by the article and by the
fast verifier. This script is intentionally lightweight; it does not change the
physics or the eigenproblem.
"""
from __future__ import annotations
from pathlib import Path
import shutil
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FULL = ROOT / 'run_full_strict_extension'
SRC_RES = FULL / 'results'
SRC_FIG = FULL / 'figures'
DST_RES = ROOT / 'recomputed_results'
DST_FIG = ROOT / 'recomputed_figures'
DST_RES.mkdir(exist_ok=True)
DST_FIG.mkdir(exist_ok=True)

CSV_ALIASES = {
    'primary_mode_grid_extension.csv': 'primary_mode_grid_extension.csv',
    'all_distinct_modes_grid_extension.csv': 'all_distinct_modes_grid_extension.csv',
    'all_shift_envelopes_grid_extension.csv': 'all_shift_envelopes_grid_extension.csv',
    'grid_UQ_apparent_order_and_Richardson.csv': 'grid_UQ_apparent_order_and_Richardson.csv',
    'horn_leakage_empirical_grid_variability_floor.csv': 'horn_leakage_empirical_grid_variability_floor.csv',
    'boundary_proxy_sensitivity.csv': 'boundary_proxy_sensitivity.csv',
    'axis_cutoff_sensitivity_PH_100x70.csv': 'axis_cutoff_sensitivity_PH_100x70.csv',
    'C3_deduplicated_modes_70x48.csv': 'C3_deduplicated_distinct_modes_70x48.csv',
    'C3_shift_window_envelope_raw.csv': 'C3_shift_window_envelope_70x48.csv',
    'm_sweep_extended_controls_70x48.csv': 'm_sweep_controls_70x48.csv',
    'geometry_matching_metrics.csv': 'geometry_matching_metrics.csv',
    'RUN_SUMMARY_final_strict_extension.txt': 'RUN_SUMMARY_final_strict_extension.txt',
}
FIG_ALIASES = {
    'fig_eta100_grid_extended.png': 'fig_eta100_grid_extended.png',
    'fig_eta100_grid_extended.png': 'fig_C2_eta100_grid_stability.png',
    'fig_leakage_vs_floor_extended.png': 'fig_leakage_vs_floor_extended.png',
    'fig_logCF_vs_slope_extended.png': 'fig_logCF_vs_slope_extended.png',
    'fig_msweep_eta_extended.png': 'fig_msweep_eta_extended.png',
    'fig_msweep_logCF_extended.png': 'fig_msweep_logCF_extended.png',
}

def copy_aliases():
    if not SRC_RES.exists():
        raise SystemExit(f'Missing full-run results directory: {SRC_RES}. Run the full calculation first.')
    for src_name, dst_name in CSV_ALIASES.items():
        src = SRC_RES / src_name
        if src.exists():
            shutil.copy2(src, DST_RES / dst_name)
            print(f'CSV {src_name} -> {dst_name}')
    if SRC_FIG.exists():
        for src_name, dst_name in FIG_ALIASES.items():
            src = SRC_FIG / src_name
            if src.exists():
                shutil.copy2(src, DST_FIG / dst_name)
                print(f'PNG {src_name} -> {dst_name}')
    # If PH/control ratios were not generated by the current full script, compute a compact one.
    p = DST_RES / 'primary_mode_grid_extension.csv'
    if p.exists():
        df = pd.read_csv(p)
        rows = []
        for grid, sub in df[df.geometry.isin(['PH','LINEAR','POLY2','SMOOTHSTEP'])].groupby('grid'):
            ph = sub[sub.geometry == 'PH']
            if ph.empty: continue
            ph = ph.iloc[0]
            for _, c in sub[sub.geometry != 'PH'].iterrows():
                rows.append({
                    'grid': grid,
                    'control': c.geometry,
                    'delta_eta100_pp': float(ph.eta_100R_pct - c.eta_100R_pct),
                    'delta_log10CF': float(ph.log10_CF - c.log10_CF),
                    'leakage_ratio_control_over_PH': float(c.horn_leakage_pct / max(ph.horn_leakage_pct, 1e-300)),
                    'raw_CF_ratio_PH_over_control': float(ph.CF_axial_inter_over_horns / max(c.CF_axial_inter_over_horns, 1e-300)),
                })
        if rows:
            pd.DataFrame(rows).to_csv(DST_RES / 'PH_vs_controls_fine_grid_ratios.csv', index=False)
            print('CSV computed -> PH_vs_controls_fine_grid_ratios.csv')

if __name__ == '__main__':
    copy_aliases()
    print('Post-processing complete.')
